os: linux
dist: xenial
language: python

cache:
  pip: true
  directories:
    - $HOME/.ccache

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=750M
    - PATH="/usr/lib/ccache:$HOME/miniconda/bin:$PATH"
    - BACKEND=c

matrix:
  include:
    - python: 3.6
      dist: xenial    # Required for Python 3.7
      env: BACKEND=c
    - python: 3.7
      dist: xenial    # Required for Python 3.7
      sudo: required
      env: BACKEND=c
    - env: STACKLESS=true BACKEND=c PY=3
      python: 3.6

# safelist
branches:
  only:
  - master


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pytest pytest-cov
  - pip install pytest-openfiles pytest-arraydiff pytest-doctestplus pytest-remotedata
  - source activate test-env
  - conda install -c eumetsat fftw3
  - pip install --upgrade pip
  - pip install --upgrade numpy mkl mkl-include
  - pip install --upgrade cython
  - pip install -r requirements-dev.txt

install:
  - python setup_cython.py build_ext --inplace

# command to run tests
script:
  -  python -m pytest --cov=./
  # - py.test
