os: linux
language: python
cache: pip
python:
  - "3.6"
branches:
  only:
  - master

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install fftw
  - pip install --upgrade pip
  - pip install --upgrade numpy mkl mkl-include
  - pip install --upgrade cython
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt
  - pip install -r requirements-dev.txt  

install:
  - python setup.py develop
script:
  - nosetests -v --nocapture --with-coverage --cover-package=mrsimulator
after_success:
  - coveralls