os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

sudo: false
cache: pip


# safelist
branches:
  only:
  - v0.1.1

before_install:
  - "pip install --upgrade pip"
  - "pip install --upgrade numpy"
  - "pip install --upgrade mkl"
  - "pip install --upgrade mkl-include"
  - "pip install --upgrade cython"

install:
  - "pip install -r requirements-dev.txt"
  - "python setup_cython.py build"
  - "python setup_cython.py install"

# command to run tests
script:
  - "pytest"
