# .travis.yml

language: python

# ===== Linux ====== #
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    packages:
      - libopenblas-dev
      - libfftw3-dev

# env:
#   # - PKG1=mkl PKG2=mkl-include
#   - PKG1=nomkl PKG2=openblas

cache:
  pip: true
  directories:
    - $HOME/.ccache

# safelist
branches:
  only:
    - master

jobs:
  include:
    # ===== Mac OS ====== #
    # Travis images doesn't work for python versions before 3.7.5
    - name: "Python 3.7.5 running on macOS 10.14.3"
      os: osx
      osx_image: xcode10.2 # Python 3.7.5 running on macOS 10.14.3
      language: shell

    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3 # Python 3.8.0 running on macOS 10.14.6
      language: shell

    # ===== Windows ====== #
    # - name: "Python 3.6.8 on Windows"
    #   os: windows # Windows 10.0.17134 N/A Build 17134
    #   language: shell # 'language: python' is an error on Travis CI Windows
    #   before_install:
    #     - choco install python --version 3.6.8
    #   env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

before_install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install codecov
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install openblas fftw
        python3 -m pip install --user -r requirements.txt
        python3 -m pip install --user -r requirements-dev.txt
    fi
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-dev.txt
    fi
  - python3 --version || python --version

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
install:
  - python3 setup.py develop || python setup.py develop

# command to run tests
script:
  - python3 -m pytest --cov=./

after_success:
  - python3 -m codecov
