name: mrsim-dev
channels:
  - anaconda
dependencies:
  - fftw>=3.3.0
  - openblas
  - pip:
      - numpy>=1.17
      - setuptools>=27.3
      - cython>=0.29.11
      - astropy>=3.0
      - requests>=2.21.0
      - matplotlib>=3.0
      - monty==2.0.4
      - csdmpy>=0.2
      - pydantic>=0.28
      - lmfit>=1.0.0
      - sphinxjp.themes.basicstrap
      - breathe>=4.13.0
      - sphinx-copybutton
      - sphinx-gallery
      - sympy
