name: mrsim # overridden at install, so this is for your use with conda env
channels:
  - anaconda
dependencies:
  - numpy>=1.13.3
  - setuptools>=27.3
  - cython>=0.29.11
  - astropy>=3.0
  - requests>=2.21.0
  - fftw>=3.3.0
  - openblas
  - pip>=19.1.1
  - pip:
      - flask>=1.1.0
      - plotly>=3.6
      - dash>=0.40
      - dash_bootstrap_components
      - gunicorn
      - monty==2.0.4
      - csdmpy>=0.1.2
      - pydantic>=0.28
