name: mrsim-dev
channels:
  - anaconda
dependencies:
  - fftw>=3.3.0
  - openblas
  - pip>=19.1.1
  - pip:
      - numpy>=1.17
      - setuptools>=27.3
      - cython>=0.29.11
      - astropy>=3.0
      - requests>=2.21.0
      - matplotlib>=3.1
      - monty>=3.0.2
      - csdmpy>=0.2.1
      - pydantic>=1.0
      - lmfit>=1.0.0
      # test
      - sympy
      - pytest<=5.3
      - pytest-cov
      # building docs
      - sphinxjp.themes.basicstrap
      - sphinx-copybutton>=0.2.11
      - sphinx-gallery>0.6.2
      - pillow>=7.1.2
      - breathe>=4.18
      - sphinx-tabs>=1.1.13
