name: mrsimulator-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - fftw>=3.3.0
  - openblas
  - numpy>=1.16
  - setuptools>=27.3
  - cython>=0.29
  - matplotlib>=3.0
  - pip
  - pip:
      - monty>=2.0.4
      - csdmpy>=0.2.1
      - pydantic>=1.0
