name: mrsim-dev
channels:
  - anaconda
dependencies:
  - fftw
  - openblas
  - numpy
  - setuptools
  - cython
  - pip:
      - monty==2.0.4
      - matplotlib
      - csdmpy
      - pydantic
      - sphinxjp.themes.basicstrap
      - breathe
      - sphinx-copybutton
      - sphinx-gallery
      - sympy
      - lmfit
