[project]
requires-python = ">=3.6"

[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.17,<1.20; python_version==3.6",
    "numpy>=1.17; python_version>3.6",
    "cython>=0.29"
]
